### PR TITLE
upgrade to netcore rtm

### PR DESCRIPTION
**Pull request by retk**
I'm proudly presenting the very first PR :sparkles: :star: 

Changes:
- updated projects to .net core 1.0.0 rtm with tooling preview 2

As there were some breaking changes between the versions, I had to change some implementation details:
- in Slamby.Common.DI namespace the Scanner and IServiceCollectionExtensions classes are changed
- in Slamby.API.Helpers.Swashbuckle namespace I had to add the missing annotation attributes.
- the Slamby.API.Helpers.Swashbuckle.RegexModelFilter class renamed to RegexSchemaFilter and now it implements ISchemaFilter
- some other smaller changes

Currently all the tests are green, though the application was not tested at all. Please review my changes, and feel free to comment.

Cheers! :v:

### CODE REVIEW

**Comment by retk** [comment]
added [change](https://github.com/slamby/slamby-api/pull/1/commits/ff066600fa18cd8bafd40ccc79db49c87aa3fd4e) with updated xproj project files. VS will now use atrifacts folder as build-base-path.

**Comment by retk** [comment]
Open question:
As the solution relies on your own docker image, it should be updated as well. Should i update the project with docker tools support and change the Dockerfile and compose.yml to use microsoft/dotnet:latest as base image? It will definitely has some advantages (VS debugging exeprience with docker) and drawbacks (more complicated dockerfile).

**Comment by attilalaszlo** [comment]
As you said we have our slambybase image, but not pushed the Dockerfile for that yet. We will do it and also push it to Docker Hub.
In that image we have already restored the most of the packages so the build process can be 5-6 minutes. 
I think we should do that for this change also.

**Comment by retk** [comment]
well, i have to admit that i had hard times dealing with some issues i encountered. 

#1 on ubuntu Socket.Connect throws PlatformNotSupportedException (see [#8768](https://github.com/dotnet/corefx/issues/8768). As a workaround I resolve redis hostnames manually.
#2 on ubuntu .netcore.app:1.0.1 fail to load native.ssl dependencies. as it's fixed in 1.1.0 i've upgraded to 1.1.0-preview-*
#3 had to fix [#793](https://github.com/aspnet/Hosting/issues/793)

and some other smaller changes...

anyway, the app is up and running. to test you can use the following dockerfile
FROM microsoft/aspnetcore:1.1.0-preview1
ARG source=.
WORKDIR /app
EXPOSE 80
COPY $source .
ENTRYPOINT ["dotnet", "Slamby.API.dll"]

don't forget to build the image against the published folder, not the source.

**Comment by retk** [comment]
to keep dotnet cli and vs in sync i changed the output directories back to the default, instead of artifacts folder. as msbuild tooling support is coming quickly, this can be done more easily soon.

**Comment by retk** [comment]
ok this pr is definitely getting longer and longer... :flushed: :scream: :construction_worker:
- in previous milestones, MVC's JSON serialization used Json.NET's default naming convention (pascal casing), in 1.0.0, MVC uses camel case names by default. see: [aspnet/Mvc#4842](https://github.com/aspnet/Mvc/issues/4842). i added a workaround to fix this.
- i updated some of the packages to the stable versions
- the class libraries are retargeted to netstandard1.6 to improve package reuseability. though I had to import "portable-net45+win8" to be able to reference Slamby.SDK.Net. (updating that package is out of scope)

Finally some good news: the API was tested with slamby-insight electron, and it seems it works without any issue. 
:clap:

**Comment by illeszsolt** [comment]
manually merged into 'master' branch

**Pull request merged**
